### ISSUE TITLE
Investigate what metadata can be retrieved for npm-install modules

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/npm-install#218]
As a part of our BOM work outlined in [this RFC](https://github.com/sophiewigmore/rfcs/blob/7f03362451a40fc3d2e5cb3d8de862b745c74180/text/0028-bill-of-materials.md), we would like to support some type of BOM metadata for modules provided by buildpacks like npm-install.

We should investigate the extent of data that can be extracted around the following for the modules provided by this buildpack:
- All of the the other information (SHA, URI, etc for each module)
 - License information
 - CPEs

### Acceptance
The outcome of this issue should be more issues that outline the work needed to implement viable metadata as a result of this investigation.

**Comment by ForestEckhardt** [comment]
There does not appear to be any straight forward tooling from NPM to facilitate the retrieval of module information. However, because the modules themselves contain `package.json` files we could walk the `node_modules` directory and parse all of the information such as name, version, license, repository, etc. out of the `package.json` itself as these are standard fields. Another benefit of this approach is that is will for for any node package manager (i.e. npm, yarn) as it relies on the contents of the `node_modules` folder as opposed to the functionality built into the package manager.

**Comment by ryanmoran** [comment]
Have you looked into https://github.com/CycloneDX/cyclonedx-node-module?

**Comment by sophiewigmore** [comment]
Just checked it out! This tool is awesome, it gets almost everything we want:
name, version, description, hash, source URI, license ID, package URL  for each node module. I'm thinking we can try to run this tool along side the npm install or yarn install buildpack.

The tool outputs in CycloneDX which will be ideal if/when we officially support CycloneDX.  For the time being, with the current TOML format we support we can likely pull the information off of the JSON, and pass it into the same BOM Generator we currently use in [node-engine](https://github.com/paketo-buildpacks/node-engine/blob/082d5ff0463cb48024aa7ab434a71ec1828796ed/build.go#L58) and [yarn](https://github.com/paketo-buildpacks/yarn/blob/7d032e5d002474bb21679553185325c02e3e6fea/build.go#L55)

**Comment by sophiewigmore** [comment]
Closing in favour of [the suite of issues](https://github.com/paketo-buildpacks/nodejs/issues/424) to implement this.
