### ISSUE TITLE
Locally installed packages not loading on container start

### ISSUE THREAD

**Issue by jonirap** [paketo-buildpacks/npm-install#525]
## Expected Behavior

When installing linked packages, ergo local and not from registry, everything should work normally and the code should be able to import the relevant packages.
## Current Behavior

Deploying the container fails because of the `setup-symlinks` command
## Possible Solution

Possibly [this line](https://github.com/paketo-buildpacks/npm-install/blob/main/cmd/setup-symlinks/internal/run.go#L64) is the issue - the linkPath is joined twice with the Resolved package.
## Steps to Reproduce

1. Create a simple npm package 
2. Install sub-package
3. Pack 
4. Run the image

## Motivations

I'm trying to run a package that is dependant on other local packages (unpublished).

**Comment by mhdawson** [comment]
This is the documentation for the `link` command - https://docs.npmjs.com/cli/v10/commands/npm-link

I recreated the reported issue with the following:



I think the key part is:

```
First, npm link in a package folder with no arguments will create a symlink in the global folder {prefix}/lib/node_modules/<package> that links to the package where the npm link command was executed. It will also link any bins in the package to {prefix}/bin/{name}. Note that npm link uses the global prefix (see npm prefix -g for its value).
```

**Comment by mhdawson** [comment]
This is the documentation for the `link` command - https://docs.npmjs.com/cli/v10/commands/npm-link

I think the key part is:

```text
First, npm link in a package folder with no arguments will create a symlink in the global folder {prefix}/lib/node_modules/<package> that links to the package where the npm link command was executed. It will also link any bins in the package to {prefix}/bin/{name}. Note that npm link uses the global prefix (see npm prefix -g for its value).
```

**Comment by mhdawson** [comment]
Turns out the global prefix does not really matter.

However, I think with the buildpacks the issue is that either

1) you have npm install your packages
2) you have pre-installed your packages

but not a mix of the two.

If there is a packge.json and package-lock.json then npm-install will kick in an assume it needs to install of the packages and it will ignore your local node_modules

If you want to do what you are doing you would need to make sure that any linked directories are under the main directory for your application (as only content from that and below would be copied over). npm install what is in your package.json, npm link your local stuff, and then remove the package.json and package-lock.json.

Easier would like be to avoid using the link command and just use:

```text
const linked = require('./linked');
```

after making sure that linked is a subdirectory of the application being built.
```

```

**Comment by mhdawson** [comment]
After trying lots of combinations I think the buildpacks are working properly.

With the right info in the package-lock.json it resolves the package and the application runs ok in the container at startup.

The problem seems to e that it is easy with npm to get into a state where the package-lock.json does not have the right info.
* npm link, npm install with no node_modules and no package-lock.json seems to work ok
* npm install, npm link with a package-lock.json fails
* npm install, npm link, removing package-lock.json fails
* npm install, npm link linked --save  worked ok

So if you find an set of commands that results in the right info in the package-lock.json then the buildpacks handle it ok. If on the other hand npm will easily give you a config that seems to have linked correctly but the package-lock.json is not updated. Since the buildpacks generate the contents based on the package-lock.json then the container will not have the dep.\



* 


While the app will run locally right after the npm link with the install, the npm install is needed so that the right information is in the package-lock.json.

If I make sure to do the npm install after the link and the linked packed is not in the app directory I get:

**Comment by mhdawson** [comment]
In summary I think the buidpacks do the right thing. If I link to a package outside of the app directory I get an error, if I link to a directory in the app directory it works. This assumes that the package-lock.json has been updated correctly which is outside the scope of the buildpacks.

I'm going to close out this issue.  @jonirap I know it has been quite a long time since you opened the issue but if its still and issue for you and what I've explained does not help you get the right behaviour please reopen.
